hugoblox:
  schema: "2.0"
  identity:
    name: Prof. Dr. Marco Kalz
    type: person
    tagline: Researcher in Educational Technology
    description: "Dr. Marco Kalz is a researcher and professor of educational technology at the Heidelberg University of Education."
    organization: Heidelberg University of Education
  theme:
    mode: system
    pack: default
    colors:
      primary: violet
      secondary: ""
      neutral: ""
  typography:
    font: sans
    size: md
    pack: editorial
  layout:
    radius: md
    spacing: comfortable
    avatar_shape: circle
  header:
    enable: true
    style: navbar
    sticky: true
    align: center
    search: true
    theme_toggle: true
  footer:
    style: minimal
    language_switcher: true
    text: Made with ❤️ in Heidelberg/Aachen and on the road.
  copyright:
    notice: © {year} {name}
    license:
      allow_derivatives: true
      allow_commercial: true
  content:
    math:
      enable: false
    toc:
      enable: true
    reading_time:
      enable: false
  search:
    enable: true
  seo:
    location:
      phone: "+496221477331"
  comments:
    enable: true
  pro:
    hide_attribution: false
  locale:
    date_format: 02.01.2006
    time_format: "15:04"
    address_format: en-US
